---
- name: Create install path
  file:
    path: "{{ rfid_tuer_ansible_install_path }}"
    state: directory

- name: Clone the rfid_tuer repository
  git:
    repo: https://github.com/stuvusIT/rfid_tuer.git
    dest: "{{ rfid_tuer_ansible_install_path }}"
    depth: 1
    force: yes

- name: Install python deps apt:
    name: "{{ item }}"
  with_items:
    - python3-pyscard
    - python3-ldap3
    - python3-yaml

- name: Enable SPI
  lineinfile: 
    dest: /etc/modprobe.d/raspi-blacklist.conf
    state: absent
    regexp: 'blacklist spi-bcm2708'

- name: Create door group
  group:
    name: "{{ rfid_tuer_ansible_group }}"

- name: Create door user
  user:
    name: "{{ rfid_tuer_ansible_user }}"
    group: "{{ rfid_tuer_ansible_group }}"

- name: Write udev rules
  copy:
    src: udev.j2
    dest: /etc/udev/rules.d/50-door.rules


- name: Place systemd service file
  template:
    src: door.service.j2
    dest: /etc/systemd/system/door.service
  notify: Restart door service

- name: Place config file
  copy:
    content: "{{ rfid_tuer_ansible_vars | to_nice_yaml }}"
    dest: "{{ rfid_tuer_ansible_install_path }}/config.yml"
    mode: 0600
    owner: "{{ rfid_tuer_ansible_user }}"
  notify: Restart door service

