---
- name: Create install path
  file:
    path: "{{ rfid_tuer_ansible_install_path }}"
    state: directory

- name: Clone the rfid_tuer repository
  git:
    repo: https://github.com/stuvusIT/rfid_tuer.git
    dest: "{{ rfid_tuer_ansible_install_path }}"
    depth: 1
    force: yes

- name: Install python deps apt and pcscd
  apt:
    name: "{{ item }}"
  with_items:
    - pcscd
    - python3-pyscard
    - python3-ldap3
    - python3-yaml
    - python3-pip

- name: Install python3-pifacecommon and pifacedigitalio
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - git+https://github.com/piface/pifacecommon
    - git+https://github.com/piface/pifacedigitalio

- name: Enable SPI
  lineinfile: 
    dest: /boot/config.txt
    state: present
    line: 'dtparam=spi=on'

- name: Create door and gpio group
  group:
    name: "{{ item }}"
  with_items:
    - "{{ rfid_tuer_ansible_group }}"
    - gpio

- name: Create door user
  user:
    name: "{{ rfid_tuer_ansible_user }}"
    groups: 
      - "{{ rfid_tuer_ansible_group }}"
      - gpio

- name: Write udev rules
  template:
    src: udev.j2
    dest: /etc/udev/rules.d/50-door.rules

- name: Place systemd service file
  template:
    src: door.service.j2
    dest: /etc/systemd/system/door.service
  notify: Restart door service

- name: Place config file
  copy:
    content: "{{ rfid_tuer_ansible_vars_default | combine(rfid_tuer_ansible_vars) | to_nice_yaml }}"
    dest: "{{ rfid_tuer_ansible_install_path }}/config.yml"
    mode: 0600
    owner: "{{ rfid_tuer_ansible_user }}"
  notify: Restart door service

